package com.example.auditlog.enums;

public enum ChainViolationType {
    MISSING_GENESIS,
    MULTIPLE_GENESIS,
    RECORD_HASH_MISMATCH,
    CONTENT_HASH_MISMATCH,
    INVALID_CONTENT_HASH,
    BROKEN_PREVIOUS_LINK,
    FORK_DETECTED,
    DISCONNECTED_RECORD,
    CYCLE_DETECTED
}
